# Linear Classification

## Initialization

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

## Data generation

In [35]:
np.random.seed(200)
N = 1000
X1 = np.hstack((2 + np.random.randn(N, 2), (np.ones((N, 1)))))
X2 = np.hstack((4 + np.random.randn(N, 2), (np.ones((N, 1)))))
X = np.vstack((X1, X2))
y1, y2 = np.ones((N, 1)), -np.ones((N, 1))
y_train = np.vstack((y1, y2))
data_matrix = np.hstack((X, y_train))
X_test_1 = np.hstack((2 + np.random.randn(N, 2), (np.ones((N, 1)))))
X_test_2 = np.hstack((4 + np.random.randn(N, 2), (np.ones((N, 1)))))
X_test = np.vstack((X_test_1, X_test_2))
y1, y2 = np.ones((N, 1)), -np.ones((N, 1))
y_test = np.vstack((y1, y2))
print(np.mean(X1, axis=0))
print(np.mean(X2, axis=0))


[1.97227706 2.02505839 1.        ]
[3.94791075 3.97267458 1.        ]


## Perceptron

In [36]:
i = 0
lr = 0.01
w = np.ones(X1.shape[1])
epoch = 100
while i == 0 and epoch != 0:
    miss_classified = 0
    for item in range(len(data_matrix)):
        x = data_matrix[item, :-1]
        y = data_matrix[item, -1]
        projection = np.dot(w, x)
        if y*projection > 0:
            continue
        else:
            w += lr*y*x
            miss_classified += 1
    print('epoch {}'.format(100 - epoch + 1))
    print('miss classified {}'.format(miss_classified))
    epoch -= 1
    if miss_classified == 0:
        i = 1

epoch 1
miss classified 33
epoch 2
miss classified 11
epoch 3
miss classified 10
epoch 4
miss classified 10
epoch 5
miss classified 10
epoch 6
miss classified 11
epoch 7
miss classified 12
epoch 8
miss classified 10
epoch 9
miss classified 11
epoch 10
miss classified 12
epoch 11
miss classified 10
epoch 12
miss classified 10
epoch 13
miss classified 11
epoch 14
miss classified 12
epoch 15
miss classified 10
epoch 16
miss classified 11
epoch 17
miss classified 10
epoch 18
miss classified 11
epoch 19
miss classified 12
epoch 20
miss classified 10
epoch 21
miss classified 10
epoch 22
miss classified 11
epoch 23
miss classified 10
epoch 24
miss classified 10
epoch 25
miss classified 10
epoch 26
miss classified 11
epoch 27
miss classified 10
epoch 28
miss classified 11
epoch 29
miss classified 10
epoch 30
miss classified 10
epoch 31
miss classified 9
epoch 32
miss classified 10
epoch 33
miss classified 11
epoch 34
miss classified 10
epoch 35
miss classified 10
epoch 36
miss classified 10
ep

In [37]:
w

array([-0.14136371, -0.15822438,  0.5       ])

## Validation 

In [38]:
y_pre = []
for i in range(len(X_test)):
    y_pre.append(np.sign(np.dot(w,X_test[i, ])))

confusion_matrix(y_pre, y_test).T

array([[1000,    0],
       [ 675,  325]], dtype=int64)

## Using sklearn package

In [39]:
from sklearn.linear_model import Perceptron

In [40]:
model = Perceptron(tol=0.001, random_state=0)
model.fit(X, y_train)

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


Perceptron()

In [41]:
y_pre = model.predict(X_test)
print(confusion_matrix(y_pre, y_test).T)
model.coef_


[[978  22]
 [159 841]]


array([[-13.02695273, -14.89075045,  37.        ]])

## Least Square method

In [42]:
a = np.linalg.inv(np.dot(X.T, X))
b = np.dot(X.T, y_train)
W = np.dot(a, b)
W

array([[-0.34818799],
       [-0.32987565],
       [ 2.0199222 ]])

In [43]:
y_pre = []
for i in range(len(X_test)):
    y_pre.append(np.sign(np.dot(w,X_test[i, ])))

confusion_matrix(y_pre, y_test)

array([[1000,  675],
       [   0,  325]], dtype=int64)